dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.9.5
  firebase_auth: ^4.11.1
  firebase_core: ^2.13.1
  printing: ^5.10.1
  pdf: ^3.10.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
